server:
  port: 7001
  servlet:
    # 所有controller路径的前缀。让网关来识别微服务
    context-path: /coupon-template

spring:
  application:
    name: eureka-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    url: jdbc:mysql://49.233.90.47:3305/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123321
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocCouponHikariCP
  redis:
    database: 0
    host: 49.233.90.47
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

# ------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 配置监控端点
info:
  app:
    name: imooc-coupon-template
    groupId: imooc-coupon-service
    artifactId: coupon-template
    version: 1.0-SNAPSHOT

# ------------------------------------------------------------------------------------------------------

logging:
  level:
    com.imooc.coupon: debug
